categories: 
  - Image reconstruction
description: 3D multi-angle TIRF image reconstruction
homepage_url: https://serpico.gitlabpages.inria.fr/matirf/
long_description: 3D multi-angle TIRF image reconstruction 
name: MATIRF
owner: sted