categories: [Segmentation]
description: StarDist
homepage_url: https://stardist.net/
long_description: Object Detection with Star-convex Shapes 
name: stardist
owner: Uwe Schmidt and Martin Weigert and Coleman Broaddus and Gene Myers
