categories: [Image reconstruction]
description: Clesperanto Deskew
homepage_url: https://github.com/clEsperanto/pyclesperanto_prototype
long_description: py-clesperanto is a prototype for clesperanto - a multi-platform multi-language framework for GPU-accelerated image processing 
name: Clesperanto Deskew
owner: Robert Haase
