categories: [Segmentation]
description: Cellpose 3D
homepage_url: https://cellpose.readthedocs.io/en/latest/index.html
long_description: Anatomical segmentation algorithm written in Python 
name: cellpose
owner: Stringer Lab
