categories: [Measure]
description: LabelsMeasure
homepage_url: 
long_description: LabelsMeasure provides the tools to generate the regions of interest from label images
name: LabelsMeasure
owner: Sylvan Prigent & Léo Maury
