categories: [Measure]
description: Differentiating nuclei according to signal intensity
homepage_url: https://github.com/clEsperanto/pyclesperanto_prototype
long_description: py-clesperanto is a prototype for clesperanto - a multi-platform multi-language framework for GPU-accelerated image processing 
name: Clesperanto Intensity Stats
owner: Robert Haase
