categories: 
  - Manipulation
description: 2D or 3D image manipulation  
homepage_url: https://gitlab.inria.fr/bioimage-it/fiji-tools/
long_description: 2D or 3D image manipulation  
name: Fiji
owner: sprigent