categories: [Segmentation]
description: Clesperanto 3D Segmentation
homepage_url: https://github.com/clEsperanto/pyclesperanto_prototype
long_description: py-clesperanto is a prototype for clesperanto - a multi-platform multi-language framework for GPU-accelerated image processing 
name: Clesperanto 3D Segmentation
owner: Robert Haase
