categories: [Spots detection]
description: Count particles with channels
homepage_url: https://github.com/clEsperanto/pyclesperanto_prototype
long_description: py-clesperanto is a prototype for clesperanto - a multi-platform multi-language framework for GPU-accelerated image processing 
name: Clesperanto Count with channels
owner: Robert Haase
