categories: 
  - Segmentation
  - Spots detection
description: 2D image segmentation  
homepage_url: https://gitlab.inria.fr/bioimage-it/fiji-tools/
long_description: 2D image segmentation using threshold and analyse particles
name: Fiji
owner: sprigent