categories: [Segmentation]
description: Clesperanto Cell Segmentation from membrane images
homepage_url: https://github.com/clEsperanto/pyclesperanto_prototype
long_description: py-clesperanto is a prototype for clesperanto - a multi-platform multi-language framework for GPU-accelerated image processing 
name: Clesperanto Cell Segmentation
owner: Robert Haase
